main: co.reasondev.prison.PrisonTokens
name: ${project.artifactId}
version: ${project.version}

description: Tokens Plugin for Spigot
author: SirReason
depend: [MVdWPlaceholderAPI]

commands:
  tokens:
    description: Main Token Command
    aliases: [token]